/* sample.js — a trigger-dense Commander list used by the "Load sample" button.
   Chosen to exercise every category the engine knows about: upkeep costs,
   each-player triggers, landfall, ETB/dies, attack triggers, sagas and statics. */
(function (global) {
  'use strict';

  global.MTGSample = {
    name: 'Atraxa Sample',
    text: [
      'Commander:',
      "1 Atraxa, Praetors' Voice",
      '',
      'Deck:',
      '1 Sol Ring',
      '1 Arcane Signet',
      '1 Smothering Tithe',
      '1 Rhystic Study',
      '1 Mystic Remora',
      '1 Esper Sentinel',
      '1 Land Tax',
      '1 Phyrexian Arena',
      '1 Necropotence',
      '1 Seedborn Muse',
      '1 Aura Shards',
      '1 Grave Pact',
      '1 Guardian Project',
      '1 Beast Whisperer',
      '1 Doubling Season',
      '1 Vorinclex, Monstrous Raider',
      '1 Lotus Cobra',
      '1 Tireless Provisioner',
      '1 Avenger of Zendikar',
      '1 Solemn Simulacrum',
      '1 Sakura-Tribe Elder',
      '1 Eternal Witness',
      '1 Reclamation Sage',
      '1 Dockside Extortionist',
      '1 Archangel of Thune',
      '1 Heliod, Sun-Crowned',
      '1 Mikaeus, the Unhallowed',
      '1 Karmic Guide',
      '1 Toski, Bearer of Secrets',
      '1 Ohran Frostfang',
      '1 Managorger Hydra',
      '1 Ghave, Guru of Spores',
      '1 Skullclamp',
      "1 Ashnod's Altar",
      '1 Sword of Feast and Famine',
      '1 The Restoration of Eiganjo',
      "1 Urza's Saga",
      '1 Court of Grace',
      '1 Bala Ged Recovery // Bala Ged Sanctuary',
      '1 Cultivate',
      "1 Kodama's Reach",
      '1 Swords to Plowshares',
      '1 Deadly Rollick',
      '1 Cyclonic Rift',
      '1 Blasphemous Act',
      '1 Command Tower',
      '1 Breeding Pool',
      '1 Overgrown Tomb',
      '1 Hallowed Fountain',
      '1 Misty Rainforest',
      '4 Forest',
      '3 Plains',
      '3 Island',
      '3 Swamp'
    ].join('\n')
  };
})(window);
